defmodule PortfolixirWeb.ApiV1ProvenanceTest do
  # Issue #766 over the API (D-4 of the 2026-09-05 triage, a precision of
  # ADR-0044 §4): a field that says where a record came from is set by the
  # system, never by the caller.
  use PortfolixirWeb.ConnCase

  import Portfolixir.WorldFixtures, only: [base_world: 1, create_security!: 1]

  alias Portfolixir.Actor
  alias Portfolixir.Catalog
  alias Portfolixir.Knowledge

  setup %{conn: conn} do
    conn =
      conn
      |> put_req_header("accept", "application/json")
      |> put_req_header("content-type", "application/json")
      |> put_req_header("authorization", "Bearer test-api-token")

    %{conn: conn}
  end

  # User story:
  # As the operator whose agent writes bookings over the API,
  # I want an import hash in a transaction body refused,
  # so that an agent can neither pre-empt nor silence a later import of the same row.
  #
  # Acceptance criteria:
  # - POST and PATCH /api/v1/transactions with import_hash answer 422 naming the field.
  test "refuses an import hash on create and update", %{conn: conn} do
    world = base_world(name: "Prov Api World")
    security = create_security!(name: "Prov Co", ticker: "PRV")

    body = %{
      "portfolio_id" => world.portfolio.id,
      "securities_account_id" => world.depot.id,
      "cash_account_id" => world.cash.id,
      "security_id" => security.id,
      "type" => "buy",
      "date" => "2026-01-02",
      "currency_code" => "EUR",
      "quantity" => "10",
      "price" => "100"
    }

    forged = Map.put(body, "import_hash", "sha256-forged")

    response =
      conn |> post("/api/v1/transactions", %{"transaction" => forged}) |> json_response(422)

    assert response["errors"]["import_hash"] == ["is set by the importer"]

    created = conn |> post("/api/v1/transactions", %{"transaction" => body}) |> json_response(201)
    assert created["data"]["import_hash"] == nil

    response =
      conn
      |> patch("/api/v1/transactions/#{created["data"]["id"]}", %{
        "transaction" => %{"import_hash" => "sha256-forged"}
      })
      |> json_response(422)

    assert response["errors"]["import_hash"] == ["is set by the importer"]
  end

  # User story:
  # As the operator reading the research log,
  # I want an entry's author to say who actually wrote it,
  # so that an agent cannot record an entry as mine or strip the machine-generated marker.
  #
  # Acceptance criteria:
  # - An entry appended over the API is the agent's whatever the body claims.
  # - machine_generated in the body is ignored; the marker is reserved for a
  #   local-model path that does not exist yet.
  test "an API-appended entry is the agent's and never machine-generated by claim", %{conn: conn} do
    security = create_security!(name: "Author Co", ticker: "AUTH")

    response =
      conn
      |> post("/api/v1/securities/#{security.id}/notes", %{
        "note" => %{
          "kind" => "evidence",
          "body" => "checked the filing",
          "source_quality" => "primary",
          "as_of" => "2026-08-01",
          "author" => "operator",
          "machine_generated" => true
        }
      })
      |> json_response(201)

    assert response["data"]["author"] == "agent"
    assert response["data"]["machine_generated"] == false

    [note] = Knowledge.list_notes(security.id)
    assert note.author == :agent
    refute note.machine_generated
  end

  # User story:
  # As the operator whose securities carry a stored logo,
  # I want an attributes update to merge rather than replace, and the logo
  # bookkeeping to be untouchable from the API,
  # so that an update cannot wipe provider attributes, forge a logo path, or lock a logo.
  #
  # Acceptance criteria:
  # - logo_* keys in the body are dropped; existing logo_* keys survive.
  # - Other keys merge with the existing map; a null value removes a key.
  test "attributes merge and the logo bookkeeping is system-owned", %{conn: conn} do
    security = create_security!(name: "Attr Co", ticker: "ATTR")

    {:ok, security} =
      Catalog.update_security(Actor.owner_ui(), security, %{
        attributes: %{"sector" => "Technology", "region" => "EU"}
      })

    {:ok, security} =
      Catalog.put_logo_attributes(security, %{
        "logo_path" => "/security_logos/#{security.id}.png",
        "logo_source" => "wikipedia"
      })

    response =
      conn
      |> patch("/api/v1/securities/#{security.id}", %{
        "security" => %{
          "attributes" => %{
            "sector" => "Health",
            "region" => nil,
            "logo_path" => "https://evil.test/pixel.png",
            "logo_locked" => true,
            "logo_source" => "manual"
          }
        }
      })
      |> json_response(200)

    attributes = response["data"]["attributes"]
    assert attributes["sector"] == "Health"
    refute Map.has_key?(attributes, "region")
    assert attributes["logo_path"] == "/security_logos/#{security.id}.png"
    assert attributes["logo_source"] == "wikipedia"
    refute Map.has_key?(attributes, "logo_locked")
  end
end
